name: warmd
description: Wanna save the earth?

version: 1.0.11+16

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  provider: ^4.3.1
  flare_flutter: ^2.0.5
  shared_preferences: ^0.5.8
  pie_chart: ^3.1.1
  url_launcher: ^5.5.0
  smart_text_view: ^0.1.0
  share: ^0.6.4+3
  cupertino_icons: ^0.1.3
  easy_localization: ^2.3.2

dev_dependencies:
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: WarmdIcons
      fonts:
        - asset: fonts/WarmdIcons.ttf
