name: warmd
description: Wanna save the earth?

version: 1.0.6+10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  provider: ^4.0.5
  flare_flutter: ^2.0.3
  shared_preferences: ^0.5.7
  pie_chart: ^3.1.1
  url_launcher: ^5.4.5
  smart_text_view: ^0.1.0
  
dev_dependencies:
  gen_lang: ^0.1.2
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: WarmdIcons
      fonts:
        - asset: fonts/WarmdIcons.ttf
