name: warmd
description: Wanna save the earth?

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none"

version: 1.4.1+29

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  adaptive_dialog: ^0.10.0+4
  cupertino_icons: ^1.0.2
  dropdown_search: ^0.4.8
  fl_chart: ^0.12.2
  flow_builder: 0.0.1-dev.9
  flutter_local_notifications: ^4.0.1
  flutter_native_timezone: ^1.0.4
  flutter_svg: ^0.20.0-nullsafety.3
  freezed: ^0.13.0-nullsafety.2
  gap: ^2.0.0-nullsafety.1
  in_app_review: ^2.0.0-nullsafety
  intl: ^0.17.0
  markup_text: ^0.2.0
  page_indicator: ^0.3.0
  provider: ^5.0.0-nullsafety.3
  share_files_and_screenshot_widgets: ^1.0.3
  shared_preferences: ^2.0.0-nullsafety

dependency_overrides:
  path_drawing: ^0.5.0-nullsafety.0 # for fl_chart to be OK until they provide a nullsafety version
  path_provider: ^2.0.0-nullsafety # for share_files_and_screenshot_widgets to be OK until they provide a nullsafety version
  url_launcher: ^6.0.0-nullsafety # for markup_text to be OK until they provide a nullsafety version

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  lint: ^1.5.1

flutter:
  generate: true # for l10n
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: VarelaRound
      fonts:
        - asset: fonts/VarelaRound-Regular.ttf
