name: warmd
description: Wanna save the earth?

version: 1.0.9+14

environment:

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  provider: ^4.1.2
  flare_flutter: ^2.0.3
  shared_preferences: ^0.5.7+3
  pie_chart: ^3.1.1
  url_launcher: ^5.4.10
  smart_text_view: ^0.1.0
  share: ^0.6.4+3
  cupertino_icons: ^0.1.3
  
dev_dependencies:
  gen_lang: ^0.1.3
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: WarmdIcons
      fonts:
        - asset: fonts/WarmdIcons.ttf
