name: warmd
description: Wanna save the earth?

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none"

version: 1.3.0+22

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  easy_localization: ^2.3.3
  fl_chart: ^0.12.0
  flow_builder: ^0.0.1-dev.9
  flutter_svg: ^0.19.1
  freezed: ^0.12.3
  in_app_review: ^1.0.3
  markup_text: ^0.2.0
  page_indicator: ^0.3.0
  provider: ^4.3.2+2
  share_files_and_screenshot_widgets: ^1.0.3
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.6
  lint: ^1.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: VarelaRound
      fonts:
        - asset: fonts/VarelaRound-Regular.ttf
